# **TensorFlow: Tensors y Variables**
Este notebook cubre los conceptos fundamentales de TensorFlow relacionados con Tensores y Variables. Vamos a ver desde lo básico hasta operaciones avanzadas como tensores dispersos, operaciones algebraicas y más.

In [1]:
import tensorflow as tf
import numpy as np

## **1️⃣ Básicos de los Tensores**
Un **tensor** es la estructura de datos principal en TensorFlow. Se pueden considerar como matrices multidimensionales. ¿Qué es un tensor?
Un tensor es la estructura de datos fundamental en TensorFlow. Es similar a los arreglos de NumPy o a las matrices en matemáticas, pero puede tener cualquier cantidad de dimensiones.

In [5]:
# Crear tensores
tensor_escalar = tf.constant(5)  # Escalar solo 1 num 
tensor_vector = tf.constant([1, 2, 3])  # Vector lista de num
tensor_matriz = tf.constant([[1, 2], [3, 4]])  # Matriz 
tensor_3D = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Tensor 3D matrices en diferentes dimensiones
print(tensor_escalar, tensor_vector, tensor_matriz, tensor_3D)

tf.Tensor(5, shape=(), dtype=int32) tf.Tensor([1 2 3], shape=(3,), dtype=int32) tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


## **2️⃣ Inicialización y Conversión de Tensores**
Podemos inicializar tensores de varias maneras y convertir entre tipos de datos.

In [8]:
# Tensores inicializados
tensor_ceros = tf.zeros([3,3])  # Matriz 3x3 de ceros
tensor_unos = tf.ones([2,2])  # Matriz 2x2 de unos
tensor_random = tf.random.uniform([3,3], minval=0, maxval=10)  # Matriz aleatoria
print(tensor_ceros,"//////////",tensor_unos,"//////////", tensor_random)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32) ////////// tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32) ////////// tf.Tensor(
[[3.2265043 6.738167  1.3875985]
 [4.373288  8.947686  9.782473 ]
 [8.341833  3.2469833 7.26876  ]], shape=(3, 3), dtype=float32)


In [13]:
# Conversión de tipos
tensor_float = tf.constant(3.1416, dtype=tf.float32)
tensor_int = tf.cast(tensor_float, dtype=tf.int32)
print(tensor_int)

tf.Tensor(3, shape=(), dtype=int32)


## **3️⃣ Indexación en Tensores, acceder a valores dentro del tensor**
Podemos acceder a elementos específicos dentro de un tensor como en NumPy.

In [19]:
tensor = tf.constant([[10, 20, 30], [40, 50, 60]])
print(tensor[0, 2].numpy())  # Acceder al segundo elemento de la primera fila
  #         fila, col

30


## **4️⃣ Operaciones Matemáticas en Tensores**
Podemos realizar operaciones matemáticas como suma, resta, multiplicación, etc.

In [21]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
print(tf.add(a, b))  # Suma de matrices
print(tf.multiply(a, b))  # Multiplicación elemento a elemento
"""
tf.multiply(a, b): Multiplicación elemento a elemento.
tf.divide(a, b): División.
"""

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


'\ntf.multiply(a, b): Multiplicación elemento a elemento.\ntf.divide(a, b): División.\n'

## **5️⃣ Operaciones de Álgebra Lineal**
TensorFlow ofrece funciones para operaciones algebraicas avanzadas.

In [23]:
# Producto matricial
matriz1 = tf.constant([[1, 2], [3, 4]])
matriz2 = tf.constant([[5, 6], [7, 8]])
producto = tf.matmul(matriz1, matriz2)  # Multiplicación matricial  
print(producto)

"""
Determinante: tf.linalg.det(A)
Inversa de una matriz: tf.linalg.inv(A)
"""

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


'\nDeterminante: tf.linalg.det(A)\nInversa de una matriz: tf.linalg.inv(A)\n'

## **6️⃣ Funciones Comunes de TensorFlow**
Algunas funciones útiles incluyen reducción de dimensiones y estadísticas básicas.

In [26]:
tensor = tf.constant([1, 2, 3, 4, 5])
print(tf.reduce_sum(tensor))  # Suma total
print(tf.reduce_mean(tensor))  # Media
print(tf.reduce_max(tensor))  # Maximo

tf.Tensor(15, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


## **7️⃣ Ragged Tensors (Tensores Irregulares)**
TensorFlow permite crear tensores de longitudes variables en cada fila.

In [36]:
import tensorflow as tf

# Crear un Ragged Tensor manualmente
ragged = tf.ragged.constant([[1, 2, 3], [4, 5], [6]])

print("Ragged Tensor:")
print(ragged)

# Acceder a elementos específicos
print("\nPrimer elemento de la primera fila:", ragged[0, 0].numpy()) #es para pilla rel valor el numpy
print("Segunda fila completa:", ragged[1].numpy()) 

# Convertir un Ragged Tensor a un Tensor normal (rellenando con ceros)
padded_tensor = ragged.to_tensor(default_value=0)
print("\nTensor normalizado con ceros:")
print(padded_tensor.numpy())

# Obtener la forma dinámica de cada fila
print("\nTamaño de cada fila:")
print(ragged.row_lengths().numpy())  

# Concatenar Ragged Tensors
ragged2 = tf.ragged.constant([[10, 20], [30], [40, 50, 60]])
concat_ragged = tf.concat([ragged, ragged2], axis=1)
print("\nRagged Tensor concatenado:")
print(concat_ragged)


Ragged Tensor:
<tf.RaggedTensor [[1, 2, 3], [4, 5], [6]]>

Primer elemento de la primera fila: 1
Segunda fila completa: [4 5]

Tensor normalizado con ceros:
[[1 2 3]
 [4 5 0]
 [6 0 0]]

Tamaño de cada fila:
[3 2 1]

Ragged Tensor concatenado:
<tf.RaggedTensor [[1, 2, 3, 10, 20], [4, 5, 30], [6, 40, 50, 60]]>


## **8️⃣ Sparse Tensors (Tensores Dispersos)**
Se usan para representar datos dispersos de forma eficiente. Son una representación eficiente de matrices dispersas, es decir, aquellas que tienen muchos ceros. En lugar de almacenar todos los ceros, solo guardan los valores no nulos y sus posiciones.

In [37]:
sparse_tensor = tf.sparse.from_dense([[1, 0, 0], [0, 0, 2], [0, 3, 0]])
print(sparse_tensor) #muestras las coordenadas donde hay otra cosa que no sea 0 y al lado
#los valores de eso que no es 0 en values=, acompanyado del tamanyop de el tnsor

# Crear un Sparse Tensor manualmente
sparse_tensor = tf.sparse.SparseTensor(
    indices=[[0, 0], [1, 2], [2, 1]],  # Posiciones de los valores diferentes de cero
    values=[1, 2, 3],  # Valores en esas posiciones
    dense_shape=[3, 3]  # Tamaño total del tensor
)

print("\nSparse Tensor:")
print(sparse_tensor)

# Convertir a un tensor denso
dense_tensor = tf.sparse.to_dense(sparse_tensor)
print("\nSparse Tensor convertido a denso:")
print(dense_tensor.numpy())

# Realizar operaciones con Sparse Tensors
sparse_tensor_2 = tf.sparse.SparseTensor(
    indices=[[0, 2], [2, 0]],
    values=[5, 6],
    dense_shape=[3, 3]
)

sum_sparse = tf.sparse.add(sparse_tensor, sparse_tensor_2)
print("\nSuma de Sparse Tensors:")
print(tf.sparse.to_dense(sum_sparse).numpy())


SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]
 [2 1]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 3], shape=(3,), dtype=int32), dense_shape=tf.Tensor([3 3], shape=(2,), dtype=int64))

Sparse Tensor:
SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]
 [2 1]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 3], shape=(3,), dtype=int32), dense_shape=tf.Tensor([3 3], shape=(2,), dtype=int64))

Sparse Tensor convertido a denso:
[[1 0 0]
 [0 0 2]
 [0 3 0]]

Suma de Sparse Tensors:
[[1 0 5]
 [0 0 2]
 [6 3 0]]


## **9️⃣ String Tensors (Tensores de Texto)**
TensorFlow permite trabajar con texto usando tensores de tipo `string`.

In [39]:
# Crear un String Tensor
string_tensor = tf.constant(["Hola", "Mundo", "TensorFlow"])

print("\nString Tensor:")
print(string_tensor.numpy())

# Convertir a mayúsculas y minúsculas
upper_tensor = tf.strings.upper(string_tensor)
lower_tensor = tf.strings.lower(string_tensor)

print("\nTexto en mayúsculas:", upper_tensor.numpy())
print("Texto en minúsculas:", lower_tensor.numpy())

# Concatenación de String Tensors
concat_string = tf.strings.join(["Hola", " ", "Mundo!"])
print("\nString concatenado:", concat_string.numpy())

# División de texto
split_text = tf.strings.split(tf.constant("Esto es TensorFlow"))
print("\nDivisión de texto en palabras:", split_text.numpy())

# Contar la cantidad de caracteres en cada palabra
char_count = tf.strings.length(string_tensor)
print("\nCantidad de caracteres en cada palabra:", char_count.numpy())



String Tensor:
[b'Hola' b'Mundo' b'TensorFlow']

Texto en mayúsculas: [b'HOLA' b'MUNDO' b'TENSORFLOW']
Texto en minúsculas: [b'hola' b'mundo' b'tensorflow']

String concatenado: b'Hola Mundo!'

División de texto en palabras: [b'Esto' b'es' b'TensorFlow']

Cantidad de caracteres en cada palabra: [ 4  5 10]


## **🔟 Variables en TensorFlow**
Las variables son tensores que pueden ser modificados durante el entrenamiento de un modelo.

In [41]:
# Crear una Variable en TensorFlow
variable = tf.Variable([1, 2, 3])

print("\nVariable inicial:", variable.numpy())

# Modificar la variable
variable.assign([4, 5, 6])
print("Variable modificada:", variable.numpy())

# Incrementar valores
variable.assign_add([1, 1, 1])
print("Variable después de suma:", variable.numpy())

# Decrementar valores
variable.assign_sub([2, 2, 2])
print("Variable después de resta:", variable.numpy())

# Variables en operaciones matemáticas
w = tf.Variable(3.0)
b = tf.Variable(1.0)

# Computar salida de una función y = w*x + b
x = tf.constant(5.0)
y = w * x + b
print("\nResultado de la función y = w*x + b:", y.numpy())



Variable inicial: [1 2 3]
Variable modificada: [4 5 6]
Variable después de suma: [5 6 7]
Variable después de resta: [3 4 5]

Resultado de la función y = w*x + b: 16.0


### **🎯 Conclusión**
En este notebook hemos explorado los conceptos fundamentales de TensorFlow relacionados con los tensores y variables. Ahora tienes una base sólida para avanzar en el desarrollo de modelos de Machine Learning y Deep Learning. 🚀